execute pathogen#infect()
set background=dark
color hybrid_material
syntax on
hi Normal guibg=NONE ctermbg=NONE
let g:airline_theme = "hybrid"
set number
set tabstop=4
set autoindent
set textwidth=80
set expandtab
set shiftwidth=4

"disable beeping on error"
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

"bind ctrl+\ to toggle nerdtree"
map <C-\> :NERDTreeToggle<CR>

"bind alt+\ to switch to nerdtree (Switch splits in order)
map <Esc>w <C-W>w
"bind ctrl+hjkl to switch between splits"
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

"set line numbers to be grey so they're visible in the material theme
highlight LineNR ctermfg=242
